name: Publish v0.19.2 Release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/publish-v0.19.2.yml"
      - "versions/Contact Manager v0.19.2/**"

jobs:
  publish-v0-19-2-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish or update v0.19.2 release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.FLVMMING_CODER_TOKEN || github.token }}
          tag_name: v0.19.2
          name: Contact Manager v0.19.2 (32)
          prerelease: false
          draft: false
          make_latest: true
          body_path: versions/Contact Manager v0.19.2/README.md
          files: versions/Contact Manager v0.19.2/ContactManager-v0.19.2-debug.apk
          fail_on_unmatched_files: true
